language: swift
osx_image: xcode9.3

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=VirgilSDKKeyknox.xcodeproj
    - IOS_FRAMEWORK_SCHEME="VirgilSDKKeyknox iOS"
    - MACOS_FRAMEWORK_SCHEME="VirgilSDKKeyknox macOS"
    - TVOS_FRAMEWORK_SCHEME="VirgilSDKKeyknox tvOS"
    - WATCHOS_FRAMEWORK_SCHEME="VirgilSDKKeyknox watchOS"
    - IOS_TEST_SCHEME="KeyknoxTestApp iOS"
    - TVOS_TEST_SCHEME="KeyknoxTestApp tvOS"
    - IOS_SDK=iphonesimulator11.3
    - MACOS_SDK=macosx10.13
    - TVOS_SDK=appletvsimulator11.3
    - WATCHOS_SDK=watchsimulator4.3
    - FRAMEWORK_NAME=VirgilSDKKeyknox

  matrix:
    - DESTINATION="OS=11.3,name=iPhone SE"            SCHEME="$IOS_FRAMEWORK_SCHEME"        SDK="$IOS_SDK"        TWO_STEP_BUILD_ENABLED="YES"    CARTHAGE_PLATFORM_NAME="iOS"        RUN_TESTS="YES"    ADDITIONAL_TESTS_SCHEME="$IOS_TEST_SCHEME"    PUBLISH_DOCS="NO"     PUBLISH_CARTHAGE="NO"     POD_LIB_LINT="NO"    SWIFT_LINT="NO"
    - DESTINATION="arch=x86_64"                       SCHEME="$MACOS_FRAMEWORK_SCHEME"      SDK="$MACOS_SDK"      TWO_STEP_BUILD_ENABLED="YES"    CARTHAGE_PLATFORM_NAME="Mac"        RUN_TESTS="YES"    ADDITIONAL_TESTS_SCHEME=""                    PUBLISH_DOCS="NO"     PUBLISH_CARTHAGE="YES"    POD_LIB_LINT="NO"    SWIFT_LINT="NO"
    - DESTINATION="OS=11.3,name=Apple TV 4K"          SCHEME="$TVOS_FRAMEWORK_SCHEME"       SDK="$TVOS_SDK"       TWO_STEP_BUILD_ENABLED="YES"    CARTHAGE_PLATFORM_NAME="tvOS"       RUN_TESTS="YES"    ADDITIONAL_TESTS_SCHEME="$TVOS_TEST_SCHEME"   PUBLISH_DOCS="NO"     PUBLISH_CARTHAGE="NO"     POD_LIB_LINT="NO"    SWIFT_LINT="YES"
    - DESTINATION="OS=4.3,name=Apple Watch - 42mm"    SCHEME="$WATCHOS_FRAMEWORK_SCHEME"    SDK="$WATCHOS_SDK"    TWO_STEP_BUILD_ENABLED="NO"     CARTHAGE_PLATFORM_NAME="watchOS"    RUN_TESTS="NO"     ADDITIONAL_TESTS_SCHEME=""                    PUBLISH_DOCS="NO"     PUBLISH_CARTHAGE="NO"     POD_LIB_LINT="YES"   SWIFT_LINT="NO"

before_install:
  - set -e
  - set -o pipefail
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - xcodebuild -version
  - xcodebuild -showsdks

  - openssl aes-256-cbc -K $encrypted_a2cb4519b0db_key -iv $encrypted_a2cb4519b0db_iv -in TestConfig.plist.enc -out Tests/Data/TestConfig.plist -d

script:
  - carthage version
  - carthage bootstrap --no-build

  - |
    if [ $SWIFT_LINT == "YES" ]; then
      brew outdated swiftlint || brew upgrade swiftlint
      swiftlint
    fi
  
  - |
    if [ $TWO_STEP_BUILD_ENABLED == "YES" ]; then
      # Build Framework
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release clean build | xcpretty;
      # Build Framework in Release and Run Tests if specified
      if [ $RUN_TESTS == "YES" ]; then
        if [ -n "$ADDITIONAL_TESTS_SCHEME" ]; then
          xcodebuild -verbose -project "$PROJECT" -scheme "$ADDITIONAL_TESTS_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug clean test;
        else
          xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug clean test;
        fi
      fi
    else
      # Build Framework
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release clean build | xcpretty;
    fi

  # Build with carthage
  - if [ $PUBLISH_CARTHAGE == "YES" ]; then
      carthage build --no-skip-current --no-use-binaries;
    fi
  
  # Check pod lib
  - if [ $POD_LIB_LINT == "YES" ]; then
      pod repo update;
      pod lib lint;
    fi

before_deploy:
  - carthage archive

deploy:
  # Upload framework to gh-releases for carthage
  - provider: releases
    api_key:
      secure: r3lHm11sD5czfr4H0j/IHgcwrJFWg7HwNK1T+ePqQ/29JDhqMv0Ypa2VU5zpco0Z4aaoKLtKY6x6+2dXR3uw1haBrMFjrhO8pOPM9lJtIKkpbdnwXhGXtsVXLJzM0DGhD8OwkFUjR7STmr4Fykm4yQ8bcIQsyuTkwVvFNeeTLKvl7+LGOtICFHokS5o6QdXdZ/ChUXomn0BAdi0SsqG0K5q47UP3eft5ICTe4eWZAKgxKPnOk2R8DSxF+18Y2Xsf1gouPOR6xcd1VygQEk9QTtSK0w5wcleCGFNhCANxUdrZdyHH81PGRDBsbPI9HAiwrX2fQqkSDcZyqd/cB4Iy68eBOI9GqLyiB1yQEJhVJEhO36IFakUIKKawzLuIIzc3Biv8AT4ZKJ8YU915oilgOgb/qPUadYB9iD3Jg25cTquyF6KV9JUZ+aoTqp04Djn+IhbrZ0Yh8bCF/dJrfmuuIVvt/JNSBSVVO+lRkFggY1JQhbbyVnXjazvekIdCum6F7wD5a4AX0uS94qjPDXi58DDopqsRlpQL1IXPeikcnH7tIwbc4zVxbQgZoVOpjXTfNdAYRqwwT/lhtINcwqlOFFuAnYWfRjjcT+4/lJRmyKuqaC9jmD5OmOzRvTKSDx3FY+/DWKzZ2Ngb8YeUgXxmAzxMhR76+D9VVj/t8cLztZM=
    file: $FRAMEWORK_NAME.framework.zip
    skip_cleanup: true
    on:
      repo: VirgilSecurity/keyknox-x
      tags: true
      condition: $PUBLISH_CARTHAGE = "YES"
